# Numpy Crash Course

In [1]:
import numpy as np

## Numpy Arrays

### List to array

In [2]:
l = [1, 2, 3]

In [3]:
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3])

In [5]:
arr = np.array(l)

In [6]:
arr.shape

(3,)

### Nested list to Matrix

In [7]:
nestedlist = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
matrix = np.array(nestedlist)

In [9]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix.shape

(3, 3)

## Numpy Range

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Ones

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace

In [17]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### Identity Matrix

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

### Uniform Distribution

In [20]:
np.random.rand(1)

array([0.55542925])

In [21]:
np.random.rand(5)

array([0.91308248, 0.2232888 , 0.24136137, 0.05155471, 0.72147658])

In [22]:
np.random.rand(3,3)

array([[0.31874565, 0.61430018, 0.93401017],
       [0.29691464, 0.75838327, 0.49609829],
       [0.44442011, 0.28052953, 0.21381535]])

### Starndard Normal Distribution (mean = 0, sd = 1)

In [23]:
np.random.randn(5)

array([-0.29650556,  0.91869534, -1.65157513,  0.61796498, -0.05878064])

In [24]:
np.random.randn(3,3)

array([[ 1.1246818 , -0.10792934, -0.43531703],
       [ 1.16612542,  1.15255636, -1.05751553],
       [-0.73701205,  0.13702417,  1.387455  ]])

### Normal Distribution

In [25]:
np.random.normal(10,1) # mean =10, sd =1

10.43201283375868

### Random Integer

In [26]:
np.random.randint(0,100) # low inclusive, high exclusive

89

In [27]:
np.random.randint(0,100,10)

array([53, 58, 86, 86, 42, 43, 62, 78, 38, 83])

### Seed

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0,50,10)

In [32]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

### Reshape

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(5,3) # new shape should fit the data

ValueError: cannot reshape array of size 25 into shape (5,3)

### Maximum and Minimum

In [35]:
# maximum 
ranarr.max()

39

In [36]:
# minimum
ranarr.min()

2

In [37]:
# index of max
ranarr.argmax()

7

In [38]:
# index of min
ranarr.argmin()

9

### Array datatype

In [39]:
ranarr.dtype

dtype('int64')

 ## Index Selection

In [40]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[3]

3

In [43]:
arr[2:4]

array([2, 3])

In [44]:
arr[:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## BroadCasting

In [46]:
arr = np.arange(0,10)

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# broadcasting operation on all elements
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# slice_arr holds the orignal array (shallow copy)
arr_slice = arr[:5]

In [51]:
arr_slice

array([0, 1, 2, 3, 4])

In [52]:
arr_slice[1] = 10

In [53]:
arr_slice

array([ 0, 10,  2,  3,  4])

In [54]:
arr

array([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [55]:
# deep copy
arr_copy = arr.copy()

In [56]:
arr_copy

array([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [57]:
arr_copy[1] = 100

In [58]:
arr_copy

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [59]:
arr

array([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

## Indexing on 2D array

In [60]:
matrix = np.arange(1,10).reshape(3,3)*5

In [61]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
matrix[1]

array([20, 25, 30])

In [63]:
matrix[1][1]

25

In [64]:
matrix[1,1]

25

In [65]:
matrix[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [66]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [68]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy Array Operations

In [69]:
arr = np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [73]:
arr/arr

<ipython-input-73-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [75]:
np.log(arr)

<ipython-input-75-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [76]:
arr.sum()

55

In [77]:
arr.mean()

5.0

In [78]:
matrix = np.arange(1,13).reshape(3,4)

In [79]:
matrix.sum()

78

In [80]:
matrix.sum(axis=0) # sum on vertical axis (accross the rows)

array([15, 18, 21, 24])

In [81]:
matrix.sum(axis=1) # sum on horizontal axis (acrsso the columns)

array([10, 26, 42])